{
 "title": "Observability Demo",
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage % (Node Exporter)",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Bytes)",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "App HTTP Health (Blackbox)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://34.6.110.173\"}",
     "legendFormat": "UP"
    }
   ]
  }
 ]
}